version: "3.8"

services:
  app:
    build:
      context: .
    volumes:
      - ./backend:/app
    restart: on-failure
    depends_on:
      - db
    command: >
      sh -c "/wait-for-it.sh db:3306 -- java -jar app.jar"

  db:
    image: mysql:8
#    ports:
#      - "3307:3306"
    env_file:
      - .env
    volumes:
      - ./mysql:/var/lib/mysql
    restart: on-failure

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf


